#!/usr/bin/env bash
set -ex

declare -r VERSIONS=("2.7.1-4.0.3")

for VERSION in "${VERSIONS[@]}"; do
  mkdir -p "images/$VERSION" || true
  m4 -DBASE_VERSION="$VERSION" Dockerfile.m4 > "images/$VERSION/Dockerfile"
done

